---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Pull image
      docker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_image:
        name: vishnutha/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator vishnutha/calculator