
---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/lib/python3.9
  tasks:
    - name: Pull image
      shell: docker pull vishnutha/calculator:latest
    - name: Running container
      shell: docker run -it -d --name calculator vishnutha/calculator